### ISSUE TITLE
[FEATURE] Setting to use consent manager data attributes

### ISSUE THREAD

**Issue by t3easy** [ayacoo/ayacoo-soundcloud#2]
Tools like the Klaro! consent manager use data-name and data-src attributes of the iframe tag for "contextual consent".
https://klaro.org/docs/tutorials/contextual_consent
A setting to change the rendering like this would help to use your extension and respect the privacy of website visitors.

**Comment by ayacoo** [comment]
@t3easy Thank you for your feature request. I will look into an option for the privateSettings and add an event to be able to change the soundcloud HTML.

However, this will take a while, as I'm still on "holiday".

**Comment by t3easy** [comment]
Thanks for the answer! Maybe I can have a look and send a PR.

**Comment by ayacoo** [comment]
Gladly! Any support is welcome :-) Do you want to bring the whole thing towards v11 or is v12 enough for you?

**Output**

I would adapt this part: https://github.com/ayacoo/ayacoo-soundcloud/blob/main/Classes/Rendering/SoundcloudRenderer.php#L52

Otherwise I would continue to save the actual HTML from Soundcloud away in the original.

**Settings**

For me, it's always a question of where the settings are best placed. If clients are to be handled differently, the SiteConfig or TypoScript would be better. My personal favourite is usually TypoScript, because you can overwrite the settings if necessary. What do you think?

I will create a separate issue/branch for the event later.

**Comment by ayacoo** [comment]
@t3easy I have created a pull request for you: https://github.com/ayacoo/ayacoo-soundcloud/pull/5

The PSR-14 event is already there for me, and that went well. For the privacy thing, I added a setting at TypoScript level. See if that's something for you. If everything is fine, I'll create a release 2.1.

**Comment by hilburger** [comment]
Hi guys! 
This is just what I needed for a friend's synth accesories website where I have started using Klaro implemented via the extension erhaweb/klaro-consent-manager by the very nice Eric Harrer! 🎉 

I got stuck at the example in the readme file. 

In the **services.yaml** I have added the lines to my existing settings: 
```yaml
services:
  TntDigital\TntSitepackageBs5\EventListener\ModifyFlexformEvent:
    tags:
      - name: event.listener
        identifier: 'news-flexParsing'
        event: TYPO3\CMS\Core\Configuration\Event\AfterFlexFormDataStructureParsedEvent

  TntDigital\TntSitepackageBs5\EventListener\SoundcloudOutputEventListener:
    tags:
      - name: event.listener
        identifier: 'soundcloud/output'
        event: Ayacoo\AyacooSoundcloud\Event\ModifySoundcloudOutputEvent
```

Then I have created the /packages/tnt_sitepackage_bs5/Classes/EventListener/SoundcloudOutputEventListener.php and added these lines: 
```php
<?php

namespace TntDigital\TntSitepackageBs5\EventListener;
use Ayacoo\AyacooSoundcloud\Event\ModifySoundcloudOutputEvent;

class SoundcloudOutputEventListener
{
    public function __invoke(ModifySoundcloudOutputEvent $event): void
    {
        $output = $event->getOutput();
        $output = str_replace('src', 'data-src', $output);
        $event->setOutput($output);
    }
}
```

Although I have cleared the caches via Maintenance the Soundcloud player(s) still are rendered with src- instead of data-src attribute. 

Am I overlooking something or do I have to wait for the 2.1 release? 

Thank you an great work, thank you!!
